# Generated by Django 4.2.1 on 2023-05-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('position', models.CharField(max_length=50, verbose_name='Lavozim')),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': "Maktab ma'muriyatidagi lavozimlar",
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50, verbose_name='Ism Familya')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tarjimai hol')),
                ('is_active', models.BooleanField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teacher.position', verbose_name='Lavozim')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='science.science', verbose_name='Mutaxassislik')),
            ],
            options={
                'verbose_name': "Maktab o'qituvchisi",
                'verbose_name_plural': "Maktab o'qituvchilari",
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SchoolAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50, verbose_name='Ism Familya')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tarjimai hol')),
                ('is_active', models.BooleanField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teacher.position', verbose_name='Lavozim')),
                ('science', models.ForeignKey(blank=True, help_text='Ixtiyoriy', on_delete=django.db.models.deletion.RESTRICT, to='science.science', verbose_name='Mutaxassislik')),
            ],
            options={
                'verbose_name': "Maktab ma'muriyati",
                'verbose_name_plural': "Maktab ma'muriyati",
                'ordering': ('-created',),
            },
        ),
    ]
