# Generated by Django 4.2.1 on 2023-05-07 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladministration',
            name='science',
            field=models.ForeignKey(blank=True, help_text='Ixtiyoriy', null=True, on_delete=django.db.models.deletion.RESTRICT, to='science.science', verbose_name='Mutaxassislik'),
        ),
    ]
