# Generated by Django 4.2.1 on 2023-05-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_created=True)),
                ('category_name', models.CharField(max_length=50, verbose_name="Bo'lim kategoriyasi")),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category safe URL')),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategorya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ('-data_created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Mavzu')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Post safe URL')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tekst')),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teacher.teacher', verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='news.category', verbose_name="Bo'lim kategoriyasi")),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ('-data_created',),
            },
        ),
    ]
