# Generated by Django 4.2.1 on 2023-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='data_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='data_updated',
        ),
        migrations.AlterField(
            model_name='category',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
