# Generated by Django 4.2.1 on 2023-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('science_name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Science name url')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ('-created',),
            },
        ),
    ]
