# Generated by Django 4.2.1 on 2023-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='science_name',
            field=models.CharField(max_length=25, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='science',
            name='slug',
            field=models.SlugField(help_text="To'ldirish shart emas! Avtomatik to'ldiriladi!", max_length=25, unique=True, verbose_name='Science name url'),
        ),
    ]
