# Generated by Django 4.2.1 on 2023-05-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('group_NumberLetter', models.CharField(help_text='1-"B" sinfi', max_length=75, verbose_name='Sinf')),
                ('description', models.TextField(blank=True, verbose_name="Sinf haqida ma'lumot")),
                ('class_curator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teacher.teacher', verbose_name='Sinf rahbari')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Maktabdagi mavjud Sinflar',
                'ordering': ('-created',),
            },
        ),
    ]
